version: '3.8'

services:
  api:
    build: ./
    entrypoint: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run test"]
    container_name: feedback-board-api-test
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: feedback-board-db-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: 