version: '3.8'

services:
  api:
    build: ./
    entrypoint: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run build:prod && npm start"]
    container_name: feedback-board-api-prod
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: feedback-board-db-prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
