name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      PORT: 8081
      DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
      JWT_SECRET: testsecret
      JWT_EXPIRES_IN: 1h
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: error
      SWAGGER_ENABLED: false


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit
